### ISSUE TITLE
Upgrading dune to 2.5+

### ISSUE THREAD

**Issue by palmskog** [coq-community/docker-base#8]
The current (pinned) version of dune is 2.4.0. However, dune 2.5.1 finally added support for extracting OCaml code from Coq files. Is there any chance dune could be upgraded to 2.5.1 in the near future so I (and others) can check extraction-based projects using dune in CI?

**Comment by erikmd** [comment]
yes, good point.
This is related to this other recent issue, https://github.com/coq-community/docker-coq/issues/6

**Comment by erikmd** [comment]
This issue is now resolved for all **docker-base** and **docker-coq** images, cf. this line of the (new) specification of the base images:

https://github.com/coq-community/docker-base/blob/2a1a976159138caf98c41acba0fb2c2ff173505b/images.yml#L9

Cc @picojulien and @palmskog - who had open this issue w.r.t. https://github.com/coq-community/templates/issues/38
